name: "Unpublish ðŸ˜°"

on:
  workflow_dispatch:
    inputs:

jobs:
  unpublish:
    name: Unpublish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GH_CI_BOT_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
          scope: '@FrancoAdN'
          
      - name: Set git credentials
        run: sh .github/prerelease/setup-git.sh

      - name: "Unpublish packages ðŸ˜°"
        run: npm unpublish @francoadn/ta-core-lib  -f
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

